apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  # generate a unique name
  # will need to be created with `kubectl create`
  generateName: codeconomy-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7654
  health:
    # waits for 30 seconds before checking health
    initialDelaySeconds: 30
    # health ping sends every 20 seconds, so let's give it 5 seconds buffer
    periodSeconds: 25
  template:
    spec:
      containers:
      - name: codeconomy
        image: gcr.io/codeconomy0/codeconomy-server:latest
        # args: ["--timeout=0"] # Change the timeout here, if you like the nodejs server to run longer.